### ISSUE TITLE
lua: APIImpl/File.lua:48: attempt to index global 'utils' (a nil value)

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/CuberitePluginChecker#24]
The table name in Utils.lua is `util`, I think that should be `utils`.

Edit: Found one more problem the function `deleteFolderContents` is recursive and the call should be then `utils.deleteFolderContents(fullName)` instead of `deleteFolderContents(fullName)`.

**Comment by NiLSPACE** [comment]
I believe this will be fixed in #23

**Comment by Seadragon91** [comment]
Don't see any changes there, but maybe they will come. Found a few more problems. I really recommend luacheck :-)

**Comment by NiLSPACE** [comment]
@xoft moved the loading of 'Utils.lua' before loading the other things.

**Comment by madmaxoft** [comment]
Both points are right and not yet addressed. So why don't you make a PR?
