### ISSUE TITLE
Scenario: Support file location relative to scenario folder

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/CuberitePluginChecker#25]
When adding redirection or using FS operations in the scenario file, the paths default to relative-to-Checker. However, it would be better to use relative-to-ScenarioFile paths, not to depend on specific Checker location.

Inspired by the difference between TravisCI and CircleCI, each clone the project out to a different folder structure.

**Comment by madmaxoft** [comment]
@NiLSPACE what do you think? I believe this will make writing scenarios easier, because it is expected that the redirections will be mostly for files that the scenario will provide alongside it, rather than files in the plugin's source folder.

**Comment by NiLSPACE** [comment]
I thought we already did this. Yes, it makes allot of sense to do this.
