### ISSUE TITLE
Add luacheck in CI

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/CuberitePluginChecker#26]
Luacheck should be added as another test in the CI.

**Comment by Seadragon91** [comment]
This are my current changes in [CuberitePluginChecker](https://github.com/Seadragon91/CuberitePluginChecker/commit/24524108c4a95be35d5f78667fbbaab0b72579c2).
I added the file `.lauchecrc`, install and run luacheck. The file will be added to the plugin directory if the plugin doesn't contain it.

**Comment by Seadragon91** [comment]
Current result from [circleci](https://circleci.com/gh/Seadragon91/CuberitePluginChecker/13).

Edit: The `q` flag filters out files from output, where luacheck doesn't detect any problems.

**Comment by madmaxoft** [comment]
This is not what I had in mind when creating this issue. I wanted LuaCheck to actually check this repo, not another plugin. Adding LuaCheck to other plugins is a matter of those plugins, not CuberitePluginChecker.

Also, the CI script is malformed now - consider that all actions listed in the `test/override` section can be run in parallel next to each other. All the setup needed for the test needs to be done on a single line.

**Comment by Seadragon91** [comment]
Ah okay sorry, will create a pull request that adds luacheck and we can discuss there about correcting problems in CuberitePluginChecker.
