### ISSUE TITLE
Provide AutoAPI and ManualAPI at the official Cuberite buildserver

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/CuberitePluginChecker#9]
It should be pretty straight-forward to provide the AutoAPI and ManualAPI files from the official buildserver - just archive the stuff together when building Cuberite.

**Comment by madmaxoft** [comment]
Files are being produced:
https://builds.cuberite.org/job/Cuberite%20Windows%20x64%20Master/lastSuccessfulBuild/artifact/AutoAPI.zip
https://builds.cuberite.org/job/Cuberite%20Windows%20x64%20Master/lastSuccessfulBuild/artifact/ManualAPI.zip
Now we need documentation for using them.

**Comment by NiLSPACE** [comment]
Sorry, stupid touchscreen detected my palm :/
